// +build !cgo,linux,mipsel

package demux

// Generated by ../gensyscall/main.c

const (
	_DMX_START           = 0x20006f29
	_DMX_STOP            = 0x20006f2a
	_DMX_SET_BUFFER_SIZE = 0x20006f2d
	_DMX_SET_FILTER      = 0x803c6f2b
	_DMX_SET_PES_FILTER  = 0x80146f2c
	_DMX_GET_PES_PIDS    = 0x400a6f2f
	_DMX_GET_STC         = 0xc0106f32
	_DMX_ADD_PID         = 0x80026f33
	_DMX_REMOVE_PID      = 0x80026f34
)
