[[constraint]]
  branch = "master"
  name = "github.com/ziutek/sched"

[[constraint]]
  branch = "master"
  name = "github.com/ziutek/textenc"

[[constraint]]
  branch = "master"
  name = "github.com/ziutek/thread"
